"""empty message

Revision ID: 03f912e909f0
Revises: 38b651a9f39f
Create Date: 2018-02-26 18:51:41.259592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f912e909f0'
down_revision = '38b651a9f39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'description')
    # ### end Alembic commands ###
