"""empty message

Revision ID: 38b651a9f39f
Revises: 
Create Date: 2018-02-24 17:43:09.659951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b651a9f39f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('business', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_customer_id'), 'service_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_records_product_id'), 'service_records', ['product_id'], unique=False)
    op.create_table('todo',
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('visit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_records_customer_id'), 'visit_records', ['customer_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('qq', sa.String(length=16), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sell_records_customer_id'), 'sell_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sell_records_product_id'), 'sell_records', ['product_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sell_record_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('hw_version', sa.String(length=64), nullable=True),
    sa.Column('soft_version', sa.String(length=64), nullable=True),
    sa.Column('ac_version', sa.String(length=64), nullable=True),
    sa.Column('dc_version', sa.String(length=64), nullable=True),
    sa.Column('manufactured_on', sa.DateTime(), nullable=True),
    sa.Column('license', sa.Integer(), nullable=True),
    sa.Column('license_to', sa.DateTime(), nullable=True),
    sa.Column('tf_capacity', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard', sa.Boolean(), nullable=True),
    sa.Column('check_ac_volt', sa.Boolean(), nullable=True),
    sa.Column('check_normal_test', sa.Boolean(), nullable=True),
    sa.Column('check_cv', sa.Boolean(), nullable=True),
    sa.Column('check_cr', sa.Boolean(), nullable=True),
    sa.Column('check_hv', sa.Boolean(), nullable=True),
    sa.Column('regulate_done', sa.Boolean(), nullable=True),
    sa.Column('regulate_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sell_record_id'], ['sell_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_sell_record_id'), 'machines', ['sell_record_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_issue',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_issue')
    op.drop_table('issues')
    op.drop_index(op.f('ix_machines_sell_record_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_sell_records_product_id'), table_name='sell_records')
    op.drop_index(op.f('ix_sell_records_customer_id'), table_name='sell_records')
    op.drop_table('sell_records')
    op.drop_table('issue_records')
    op.drop_table('customers')
    op.drop_index(op.f('ix_visit_records_customer_id'), table_name='visit_records')
    op.drop_table('visit_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('todo')
    op.drop_index(op.f('ix_service_records_product_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_customer_id'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_table('products')
    op.drop_table('product_config')
    op.drop_table('companies')
    # ### end Alembic commands ###
