"""empty message

Revision ID: b904dcd28889
Revises: fdb72c6f28e2
Create Date: 2018-02-09 11:36:15.667245

"""

# revision identifiers, used by Alembic.
revision = 'b904dcd28889'
down_revision = 'fdb72c6f28e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###
