"""empty message

Revision ID: d47342b815f3
Revises: b904dcd28889
Create Date: 2018-02-22 16:19:12.702028

"""

# revision identifiers, used by Alembic.
revision = 'd47342b815f3'
down_revision = 'b904dcd28889'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sell_record_id', sa.Integer(), nullable=True),
    sa.Column('hw_version', sa.String(length=64), nullable=True),
    sa.Column('soft_version', sa.String(length=64), nullable=True),
    sa.Column('ac_version', sa.String(length=64), nullable=True),
    sa.Column('dc_version', sa.String(length=64), nullable=True),
    sa.Column('manufactured_on', sa.DateTime(), nullable=True),
    sa.Column('license', sa.Integer(), nullable=True),
    sa.Column('license_to', sa.DateTime(), nullable=True),
    sa.Column('tf_capacity', sa.Integer(), nullable=True),
    sa.Column('mouse_keyboard', sa.Boolean(), nullable=True),
    sa.Column('check_ac_volt', sa.Boolean(), nullable=True),
    sa.Column('check_normal_test', sa.Boolean(), nullable=True),
    sa.Column('check_cv', sa.Boolean(), nullable=True),
    sa.Column('check_cr', sa.Boolean(), nullable=True),
    sa.Column('check_hv', sa.Boolean(), nullable=True),
    sa.Column('regulate_done', sa.Boolean(), nullable=True),
    sa.Column('regulate_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sell_record_id'], ['sell_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_sell_record_id'), 'machine', ['sell_record_id'], unique=False)
    op.add_column(u'issues', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column(u'issues', 'product_id')
    op.drop_index(op.f('ix_machine_sell_record_id'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###
