"""empty message

Revision ID: fdb72c6f28e2
Revises: None
Create Date: 2018-02-09 11:04:29.315305

"""

# revision identifiers, used by Alembic.
revision = 'fdb72c6f28e2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'authenticated')
    op.drop_table('product_config')
    # ### end Alembic commands ###
